version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rehearsal_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rehearsal_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://rehearsal_user:secret@db:5432/rehearsal_db
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  postgres_data: